# Generated by Django 3.2.4 on 2021-06-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20210619_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='blog',
        ),
        migrations.DeleteModel(
            name='BlogModel',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
